"""Kernels discovered via LLM-guided search (ZMLX Discover).

Files in this directory are auto-generated by ``python -m zmlx.discover export``.
Each file contains a single kernel discovered to be faster than the baseline
for a specific target on specific hardware.

To regenerate: run ``python -m zmlx.discover autorun`` then export winners.
See ``docs/DISCOVER_PLAYBOOK.md`` for the full workflow.
"""
